name: sample_btc_tracker
description: "A sample Flutter application to track and convert Bitcoin prices in USD, GBP, and EUR with real-time updates, built with Clean Architecture, BLoC, and GetIt."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  cupertino_icons:
  dartz: ^0.10.1
  dio: ^5.9.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  go_router: ^16.1.0
  injectable: ^2.5.1
  intl: ^0.20.0
  json_annotation: ^4.9.0
  logger: ^2.6.1
  meta: ^1.16.0
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  shimmer_animation: ^2.2.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.11.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  go_router_builder: ^3.2.0
  golden_toolkit: ^0.15.0
  injectable_generator: ^2.8.1
  json_serializable: ^6.10.0
  mockito: ^5.5.0
  test: ^1.25.15

flutter_gen:
  line_length: 100

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 200
